version: '3.8'
services:
  dev-environment:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${IMAGE_NAME:-default-image-name}"
    container_name: "${CONTAINER_NAME:-default-container-name}"
    volumes:
      - .:/home/developer:cached
      - ~/.ssh:/home/developer/.ssh:cached
    environment:
      - USER=developer
    working_dir: /home/developer
    stdin_open: true
    tty: true
